"""Create table Transactional Data

Revision ID: b5107b7d74ee
Revises: 
Create Date: 2024-07-28 19:45:53.963995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5107b7d74ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactional_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('private', sa.Integer(), nullable=True),
    sa.Column('incompleto', sa.Integer(), nullable=True),
    sa.Column('data_da_ultima_compra', sa.Date(), nullable=True),
    sa.Column('ticket_medio', sa.Float(), nullable=True),
    sa.Column('ticket_da_ultima_compra', sa.Float(), nullable=True),
    sa.Column('loja_mais_frequente', sa.String(length=100), nullable=True),
    sa.Column('loja_da_ultima_compra', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactional_data_id'), 'transactional_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactional_data_id'), table_name='transactional_data')
    op.drop_table('transactional_data')
    # ### end Alembic commands ###
